using './functions.module.bicep'

param azurewebjobsstorage_outputs_blobendpoint = '{{ .Env.AZUREWEBJOBSSTORAGE_BLOBENDPOINT }}'
param azurewebjobsstorage_outputs_queueendpoint = '{{ .Env.AZUREWEBJOBSSTORAGE_QUEUEENDPOINT }}'
param azurewebjobsstorage_outputs_tableendpoint = '{{ .Env.AZUREWEBJOBSSTORAGE_TABLEENDPOINT }}'
param functions_containerimage = '{{ .Image }}'
param functions_identity_outputs_clientid = '{{ .Env.FUNCTIONS_IDENTITY_CLIENTID }}'
param functions_identity_outputs_id = '{{ .Env.FUNCTIONS_IDENTITY_ID }}'
param readrappserviceenvironment_outputs_azure_container_registry_endpoint = '{{ .Env.READRAPPSERVICEENVIRONMENT_AZURE_CONTAINER_REGISTRY_ENDPOINT }}'
param readrappserviceenvironment_outputs_azure_container_registry_managed_identity_client_id = '{{ .Env.READRAPPSERVICEENVIRONMENT_AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_CLIENT_ID }}'
param readrappserviceenvironment_outputs_azure_container_registry_managed_identity_id = '{{ .Env.READRAPPSERVICEENVIRONMENT_AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}'
param readrappserviceenvironment_outputs_planid = '{{ .Env.READRAPPSERVICEENVIRONMENT_PLANID }}'
param readrstorage_outputs_blobendpoint = '{{ .Env.READRSTORAGE_BLOBENDPOINT }}'
param readrstorage_outputs_queueendpoint = '{{ .Env.READRSTORAGE_QUEUEENDPOINT }}'
